### ISSUE TITLE
How to generate attribute labels for different data set?

### ISSUE THREAD

**Issue by Pinak17** [steven413d/AACNN#1]
Two files ('label_train.txt' and 'label_test.txt') as mentioned are attribute labels for train and test. I am implementing this method for a different data set.
How should I generate these two files for a particular data set? 

Thank you.

**Comment by steven413d** [comment]
('label_train.txt' and 'label_test.txt') is the attribute label from [CelebA](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html). If your dataset doesn't have attribute label, you can try to train an attribute predictor by CelebA and test it on your dataset.

**Comment by Pinak17** [comment]
Thank you for your reply.
When I do train attribute predictors by CelebA on my dataset...the output images are coming blank.

**Comment by steven413d** [comment]
I have not tried it before. Maybe you can reduce the number of attribute types and only choose the attribute with high classification accuracy.

**Comment by Pinak17** [comment]
Seems like a possible solution.
Thank you.
